---
name: purple_task
description: Simple TO-DO app to help you get stuff done
publish_to: none
version: 1.2.1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  intl: ^0.17.0
  url_launcher: ^6.0.2
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 85dde09b702a0cb1f5e1392d2f030bdc3d4e5be3
  # local package
  ant_icons:
    path: packages/ant_icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0
  build_runner: null
flutter:
  uses-material-design: true
  assets:
    - assets/images/
